name = "numero-quest"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "numero-quest-db"
database_id = "7f296301-d4a8-4a5b-9aa4-a4e565ffe94a"
